defaults:
  - trainer: neuroevolution_trainer
  - dataset: mnist_dataset
  - model: mnist_fcn
  - optimizer: adam
  - _self_

generations: 200
population: 1500
device: cuda
criterion:
  _target_: torch.nn.CrossEntropyLoss